# Site
repository: cyberimp/cyberimp.github.io
favicon: images/favicon.ico
github: [metadata]
lang: ru

# Content configuration version
version: 2

# Personal info
name: Каликин Андрей
title: Middle Unity Developer
email: kinzo.x.beato@gmail.com
website: cyberimp.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespi
github_username:  cyberimp
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
  - title: Мой телеграм
    icon: fab fa-telegram-plane
    url: https://t.me/ovoshi
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-27RWTL36CM"
# google_analytics: "UA-191465132-1"

## About Section
about_title: Обо мне
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Меня зовут Андрей, я уверенный пользователь <mark>Linux</mark>, имею опыт в <mark>разработке ПО</mark>
  для <mark>ПК</mark> и <mark>Android</mark> и уверенные познания в <mark>математике</mark>,
  <mark>теории алгоритмов</mark> и <mark>паттернах разработки</mark>. Так же умею пользоваться
  <mark>git</mark>, освоил <mark>Java</mark>, <mark>Android SDK</mark>, <mark>Unity</mark>
  (<mark>C#</mark>,<mark>UniRX</mark>), <mark>Node.JS</mark>(<mark>Express</mark>,
  <mark>Sequelize</mark>), <mark>C++</mark>

content:
  - title: Портфолио # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Пыль
        link: https://github.com/cyberimp/Dust
        # link_text: Project Website
        additional_links:
          - title:  github
            icon: fab fa-github
            url: https://github.com/cyberimp/Dust
          - title:  youtube demo
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=3RvzxkCBcSo

          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Прототип аркады
        description: | # this will include new lines to allow paragraphs
          Прототип аркады на <mark>Unity</mark>, с <mark>REST</mark> бекэндом

      - layout: top-middle
        title: ru_touhou
        link: sourceforge.net/p/touhou/code/HEAD/tree/trunk/
        # link_text: Project Website
        additional_links:
          - title:  ru_touhou sourceforge
            icon: fas fa-hammer
            url: https://sourceforge.net/p/touhou/code/HEAD/tree/trunk/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Движок для скроллшутера с нуля
        description: | # this will include new lines to allow paragraphs
          Движок на <mark>C++</mark>, с использованием <mark>OpenGL</mark> для рендера,
          <mark>SDL_sound</mark> для звука, <mark>LUA</mark> для скриптинга, код хостился на <mark>SVN</mark>.

      - layout: top-middle
        title: Asteroids
        link: github.com/cyberimp/Asteroids
        # link_text: Project Website
        additional_links:
          - title: GitHub проекта
            icon: fab fa-github
            url: https://github.com/cyberimp/Asteroids
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Клон Atari Asteroids со сменным рендером, меняющимся по нажатию кнопки
        description: | # this will include new lines to allow paragraphs
          Движок на <mark>C#</mark>, с использованием <mark>OpenGL</mark> для рендера,
          код хостится на <mark>git</mark>.

      - layout: top-middle
        title: Pixchange bot
        link: pixchange.herokuapp.com
        # link_text: Project Website
        additional_links:
          - title: GitHub проекта
            icon: fab fa-github
            url: https://github.com/cyberimp/Pixchange
          - title: Сайт проекта
            icon: fas fa-globe
            url: https://pixchange.herokuapp.com
          - title: Бот проекта
            icon: fab fa-telegram-plane
            url: https://t.me/PixChangeBot
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Бот для телеметрии, отсылающий сообщение в телеграм при загрузке изображения по ссылке.
        description: | # this will include new lines to allow paragraphs
          Написан на <mark>Node.js</mark>, использует <mark>SQL</mark> для хранения пользователей и <mark>AWS</mark> для хранения картинок, хостится на <mark>Heroku</mark>.

      - layout: top-middle
        title: Spectrum Poweramp Visualisation
        link: https://play.google.com/store/apps/details?id=spectrum.poweramp.vis
        # link_text: Project Website
        additional_links:
          - title: Страница приложения в Play Market
            icon: fab fa-google-play
            url: https://play.google.com/store/apps/details?id=spectrum.poweramp.vis

          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Каталог визуализаций для Poweramp
        description: | # this will include new lines to allow paragraphs
          Написан на <mark>Java</mark>/<mark>Android SDK</mark>, кастомные View, очень много анимаций, с использованием рекламы <mark>Appodeal</mark>.

  - title: Опыт работы # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Фриланс/личные проекты
        #link: boringcompany.com
        # link_text: boringcompany.com
        #sub_title: Senior Network System Administrator
        caption: По настоящее время
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Разработка ПО на <mark>Java</mark>, <mark>C#</mark>, иногда за плату.

      - layout: left
        title: Twocookies
        sub_title: Unity Middle Developer
        caption: декабрь 2017 &mdash; март 2019
        quote: >
          Компания-разработчик мобильных игр
        description: |
          Разработка игр и приложений на <mark>Unity</mark>, в основном <mark>AR</mark>
          с использованием библиотеки <mark>Vuforia</mark>, получил навыки
          <mark>удалённой работы</mark>

      - layout: left
        title: ООО “Ладога-Энерго”
        link: ladoga-energo.ru
        # link_text: boringcompany.com
        sub_title: Администратор вычислительной сети
        caption: июнь 2017 &mdash; ноябрь 2017
        quote: >
            Предприятие по производству электрораспределительных устройств низкого напряжения
        description: | # this will include new lines to allow paragraphs
            Поддержка <mark>бесперебойной работы</mark> <mark>компьютеров и сети</mark> административного комплекса завода, монтаж рабочих станций у станков. В основном настраивал на серверах 1С Предприятие.

      - layout: left
        title: ООО “Новые Промышленные Технологии”
        # link: ladoga-energo.ru
        # link_text: boringcompany.com
        sub_title: Системный администратор
        caption: июнь 2014 &mdash; сентябрь 2015
        quote: >
            Компания, осуществляющая аутсорс обслуживание вычислительных сетей
        description: | # this will include new lines to allow paragraphs
            Поддержка <mark>бесперебойной работы</mark> парка из <mark>75 компьютеров</mark> проектной организации “Криогазтех” + выезды на другие объекты. <mark>ITIL</mark>, сервера <mark>AD</mark>, <mark>DNS</mark>, <mark>Asterisk</mark>, <mark>Лоцман</mark>.

  - title: Образование # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Физико-механический инженерный колледж
        link: https://cyberimp.github.io/otso_city
        caption: Техник
        sub_title: Программное обеспечение вычислительных комплексов, систем и сетей
        quote: >
          Сейчас называется “Технический колледж управления и коммерции”
        description: | # this will include new lines to allow paragraphs
          За время обучения научился ключевым аспектам &mdash; работе в команде и
          завершению работы до дедлайна, так же изучал <mark>C</mark>, <mark>SQL</mark>,
          <mark>Object Pascal</mark>, <mark>PHP</mark> и <mark>perl</mark>, получил
          необходимые знания в <mark>математике</mark> и <mark>теории алгоритмов</mark>
          для самостоятельного создания ПО.

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
